-- roles
CREATE TYPE public.app_role AS ENUM ('admin','cashier');

CREATE TABLE public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "profiles_read" ON public.profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "profiles_update_own" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

CREATE TABLE public.user_roles (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role public.app_role NOT NULL DEFAULT 'cashier',
  UNIQUE (user_id, role)
);
GRANT SELECT ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "user_roles_read_own" ON public.user_roles FOR SELECT TO authenticated USING (auth.uid() = user_id);

CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.app_role)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role);
$$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name)
  VALUES (NEW.id, COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email,'@',1)))
  ON CONFLICT (id) DO NOTHING;
  INSERT INTO public.user_roles (user_id, role) VALUES (NEW.id, 'cashier')
  ON CONFLICT (user_id, role) DO NOTHING;
  RETURN NEW;
END;
$$;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- catalog
CREATE TABLE public.categories (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name_en text NOT NULL,
  name_bn text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.categories TO authenticated;
GRANT ALL ON public.categories TO service_role;
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "categories_all_auth" ON public.categories FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.products (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category_id uuid REFERENCES public.categories(id) ON DELETE SET NULL,
  name_en text NOT NULL,
  name_bn text NOT NULL,
  sku text NOT NULL UNIQUE,
  price numeric(12,2) NOT NULL DEFAULT 0,
  cost numeric(12,2) NOT NULL DEFAULT 0,
  stock integer NOT NULL DEFAULT 0,
  low_stock_at integer NOT NULL DEFAULT 5,
  unit text NOT NULL DEFAULT 'pcs',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.products TO authenticated;
GRANT ALL ON public.products TO service_role;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "products_all_auth" ON public.products FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE TABLE public.sales (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_no bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  cashier_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  customer_name text,
  customer_phone text,
  subtotal numeric(12,2) NOT NULL DEFAULT 0,
  discount numeric(12,2) NOT NULL DEFAULT 0,
  tax numeric(12,2) NOT NULL DEFAULT 0,
  total numeric(12,2) NOT NULL DEFAULT 0,
  paid numeric(12,2) NOT NULL DEFAULT 0,
  payment_method text NOT NULL DEFAULT 'cash',
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.sales TO authenticated;
GRANT ALL ON public.sales TO service_role;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
CREATE POLICY "sales_read_auth" ON public.sales FOR SELECT TO authenticated USING (true);
CREATE POLICY "sales_insert_auth" ON public.sales FOR INSERT TO authenticated WITH CHECK (auth.uid() = cashier_id);

CREATE TABLE public.sale_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sale_id uuid NOT NULL REFERENCES public.sales(id) ON DELETE CASCADE,
  product_id uuid REFERENCES public.products(id) ON DELETE SET NULL,
  name_snapshot text NOT NULL,
  unit_price numeric(12,2) NOT NULL DEFAULT 0,
  quantity integer NOT NULL DEFAULT 1,
  line_total numeric(12,2) NOT NULL DEFAULT 0
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.sale_items TO authenticated;
GRANT ALL ON public.sale_items TO service_role;
ALTER TABLE public.sale_items ENABLE ROW LEVEL SECURITY;
CREATE POLICY "sale_items_read_auth" ON public.sale_items FOR SELECT TO authenticated USING (true);
CREATE POLICY "sale_items_insert_auth" ON public.sale_items FOR INSERT TO authenticated WITH CHECK (true);

-- stock decrement
CREATE OR REPLACE FUNCTION public.decrement_stock()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.product_id IS NOT NULL THEN
    UPDATE public.products SET stock = stock - NEW.quantity, updated_at = now() WHERE id = NEW.product_id;
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER on_sale_item_insert AFTER INSERT ON public.sale_items
FOR EACH ROW EXECUTE FUNCTION public.decrement_stock();

-- seed
INSERT INTO public.categories (id, name_en, name_bn) VALUES
 ('11111111-1111-4111-8111-111111111111','Grocery','মুদি'),
 ('22222222-2222-4222-8222-222222222222','Beverages','পানীয়'),
 ('33333333-3333-4333-8333-333333333333','Snacks','স্ন্যাকস'),
 ('44444444-4444-4444-8444-444444444444','Household','গৃহস্থালি');

INSERT INTO public.products (category_id, name_en, name_bn, sku, price, cost, stock, unit) VALUES
 ('11111111-1111-4111-8111-111111111111','Miniket Rice 5kg','মিনিকেট চাল ৫ কেজি','SKU-1001',420,390,40,'bag'),
 ('11111111-1111-4111-8111-111111111111','Soyabean Oil 1L','সয়াবিন তেল ১ লিটার','SKU-1002',175,162,60,'btl'),
 ('11111111-1111-4111-8111-111111111111','Masoor Dal 1kg','মসুর ডাল ১ কেজি','SKU-1003',135,120,35,'kg'),
 ('11111111-1111-4111-8111-111111111111','Sugar 1kg','চিনি ১ কেজি','SKU-1004',125,115,25,'kg'),
 ('11111111-1111-4111-8111-111111111111','Salt 1kg','লবণ ১ কেজি','SKU-1005',42,36,80,'kg'),
 ('22222222-2222-4222-8222-222222222222','Coca-Cola 1.25L','কোকা-কোলা ১.২৫ লি','SKU-2001',95,84,50,'btl'),
 ('22222222-2222-4222-8222-222222222222','Pran Mango Juice','প্রাণ ম্যাংগো জুস','SKU-2002',35,29,120,'pcs'),
 ('22222222-2222-4222-8222-222222222222','Fresh Milk 1L','ফ্রেশ দুধ ১ লিটার','SKU-2003',100,90,30,'pkt'),
 ('22222222-2222-4222-8222-222222222222','Tea Leaf 400g','চা পাতা ৪০০ গ্রাম','SKU-2004',210,190,18,'pkt'),
 ('33333333-3333-4333-8333-333333333333','Potato Crackers','পটেটো ক্র্যাকার্স','SKU-3001',20,15,150,'pcs'),
 ('33333333-3333-4333-8333-333333333333','Biscuit Energy Plus','এনার্জি প্লাস বিস্কুট','SKU-3002',30,24,90,'pkt'),
 ('33333333-3333-4333-8333-333333333333','Chocolate Bar','চকলেট বার','SKU-3003',50,41,70,'pcs'),
 ('33333333-3333-4333-8333-333333333333','Instant Noodles','ইনস্ট্যান্ট নুডলস','SKU-3004',24,19,200,'pkt'),
 ('44444444-4444-4444-8444-444444444444','Detergent Powder 500g','ডিটারজেন্ট পাউডার ৫০০ গ্রাম','SKU-4001',115,100,45,'pkt'),
 ('44444444-4444-4444-8444-444444444444','Bath Soap','গোসলের সাবান','SKU-4002',55,46,110,'pcs'),
 ('44444444-4444-4444-8444-444444444444','Toothpaste 100g','টুথপেস্ট ১০০ গ্রাম','SKU-4003',130,112,40,'pcs'),
 ('44444444-4444-4444-8444-444444444444','Tissue Box','টিস্যু বক্স','SKU-4004',85,72,4,'box');