
-- Cash / bank / mobile accounts
CREATE TABLE public.accounts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  type text NOT NULL DEFAULT 'cash',
  bank_name text,
  branch text,
  account_number text,
  opening_balance numeric NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.accounts TO authenticated;
GRANT ALL ON public.accounts TO service_role;
ALTER TABLE public.accounts ENABLE ROW LEVEL SECURITY;
CREATE POLICY accounts_all_auth ON public.accounts FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE TRIGGER accounts_updated_at BEFORE UPDATE ON public.accounts
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Chart of accounts
CREATE TABLE public.ledger_accounts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name_en text NOT NULL,
  name_bn text NOT NULL,
  class text NOT NULL DEFAULT 'expense',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ledger_accounts TO authenticated;
GRANT ALL ON public.ledger_accounts TO service_role;
ALTER TABLE public.ledger_accounts ENABLE ROW LEVEL SECURITY;
CREATE POLICY ledger_accounts_all_auth ON public.ledger_accounts FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE TRIGGER ledger_accounts_updated_at BEFORE UPDATE ON public.ledger_accounts
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Journal vouchers
CREATE TABLE public.journal_entries (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  voucher_no bigint GENERATED BY DEFAULT AS IDENTITY,
  entry_date date NOT NULL DEFAULT CURRENT_DATE,
  narration text,
  reference text,
  user_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.journal_entries TO authenticated;
GRANT ALL ON public.journal_entries TO service_role;
ALTER TABLE public.journal_entries ENABLE ROW LEVEL SECURITY;
CREATE POLICY journal_entries_all_auth ON public.journal_entries FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE TRIGGER journal_entries_updated_at BEFORE UPDATE ON public.journal_entries
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TABLE public.journal_lines (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  entry_id uuid NOT NULL REFERENCES public.journal_entries(id) ON DELETE CASCADE,
  ledger_account_id uuid REFERENCES public.ledger_accounts(id) ON DELETE SET NULL,
  account_id uuid REFERENCES public.accounts(id) ON DELETE SET NULL,
  debit numeric NOT NULL DEFAULT 0,
  credit numeric NOT NULL DEFAULT 0,
  note text,
  created_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.journal_lines TO authenticated;
GRANT ALL ON public.journal_lines TO service_role;
ALTER TABLE public.journal_lines ENABLE ROW LEVEL SECURITY;
CREATE POLICY journal_lines_all_auth ON public.journal_lines FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE INDEX journal_lines_entry_idx ON public.journal_lines(entry_id);

-- Deposits, withdrawals and transfers
CREATE TABLE public.account_transactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  type text NOT NULL DEFAULT 'deposit',
  account_id uuid REFERENCES public.accounts(id) ON DELETE SET NULL,
  to_account_id uuid REFERENCES public.accounts(id) ON DELETE SET NULL,
  amount numeric NOT NULL DEFAULT 0,
  note text,
  txn_date date NOT NULL DEFAULT CURRENT_DATE,
  user_id uuid,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.account_transactions TO authenticated;
GRANT ALL ON public.account_transactions TO service_role;
ALTER TABLE public.account_transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY account_transactions_all_auth ON public.account_transactions FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE TRIGGER account_transactions_updated_at BEFORE UPDATE ON public.account_transactions
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

INSERT INTO public.accounts (name, type, opening_balance) VALUES ('Cash in hand', 'cash', 0);

INSERT INTO public.ledger_accounts (code, name_en, name_bn, class) VALUES
  ('1000','Cash & Bank','ক্যাশ ও ব্যাংক','asset'),
  ('1100','Accounts Receivable','প্রাপ্য হিসাব','asset'),
  ('1200','Inventory','মজুদ পণ্য','asset'),
  ('2000','Accounts Payable','প্রদেয় হিসাব','liability'),
  ('3000','Owner Equity','মালিকের মূলধন','equity'),
  ('4000','Sales Revenue','বিক্রয় আয়','income'),
  ('4100','Other Income','অন্যান্য আয়','income'),
  ('5000','Cost of Goods Sold','বিক্রীত পণ্যের ব্যয়','expense'),
  ('5100','Operating Expense','পরিচালন ব্যয়','expense'),
  ('5200','Salary Expense','বেতন ব্যয়','expense');
