// Auto-generated list of images shipped with the site (public/products).
export const SITE_PRODUCT_IMAGES: { url: string; name: string }[] = [
  { url: "/products/a4-paper-500-sheet.jpg", name: "A4 Paper 500 Sheet" },
  { url: "/products/aluminium-foil-10m.jpg", name: "Aluminium Foil 10M" },
  { url: "/products/anchor-dal-1kg.jpg", name: "Anchor Dal 1Kg" },
  { url: "/products/apple-1kg.jpg", name: "Apple 1Kg" },
  { url: "/products/atta-2kg.jpg", name: "Atta 2Kg" },
  { url: "/products/baby-diaper-m-30pcs.jpg", name: "Baby Diaper M 30Pcs" },
  { url: "/products/baby-lotion-200ml.jpg", name: "Baby Lotion 200Ml" },
  { url: "/products/baby-wipes-80pcs.jpg", name: "Baby Wipes 80Pcs" },
  { url: "/products/ball-pen-10pcs.jpg", name: "Ball Pen 10Pcs" },
  { url: "/products/banana.jpg", name: "Banana" },
  { url: "/products/bath-soap.jpg", name: "Bath Soap" },
  { url: "/products/beef-1kg.jpg", name: "Beef 1Kg" },
  { url: "/products/besan-500g.jpg", name: "Besan 500G" },
  { url: "/products/biscuit-energy-plus.jpg", name: "Biscuit Energy Plus" },
  { url: "/products/body-lotion-200ml.jpg", name: "Body Lotion 200Ml" },
  { url: "/products/bread.jpg", name: "Bread" },
  { url: "/products/broiler-chicken-1kg.jpg", name: "Broiler Chicken 1Kg" },
  { url: "/products/bun-6pcs.jpg", name: "Bun 6Pcs" },
  { url: "/products/butter-200g.jpg", name: "Butter 200G" },
  { url: "/products/butter.jpg", name: "Butter" },
  { url: "/products/cashew-nut-250g.jpg", name: "Cashew Nut 250G" },
  { url: "/products/chanachur-350g.jpg", name: "Chanachur 350G" },
  { url: "/products/cheese-slice-200g.jpg", name: "Cheese Slice 200G" },
  { url: "/products/chicken-nugget-250g.jpg", name: "Chicken Nugget 250G" },
  { url: "/products/chili-powder-200g.jpg", name: "Chili Powder 200G" },
  { url: "/products/chinigura-rice-1kg.jpg", name: "Chinigura Rice 1Kg" },
  { url: "/products/chips.jpg", name: "Chips" },
  { url: "/products/chocolate-bar.jpg", name: "Chocolate Bar" },
  { url: "/products/chocolate.jpg", name: "Chocolate" },
  { url: "/products/chola-boot-1kg.jpg", name: "Chola Boot 1Kg" },
  { url: "/products/coca-cola-125l.jpg", name: "Coca Cola 125L" },
  { url: "/products/cocola-egg-noodles-500g.jpg", name: "Cocola Egg Noodles 500G" },
  { url: "/products/coffee.jpg", name: "Coffee" },
  { url: "/products/cola.jpg", name: "Cola" },
  { url: "/products/coriander-powder-200g.jpg", name: "Coriander Powder 200G" },
  { url: "/products/cumin-powder-100g.jpg", name: "Cumin Powder 100G" },
  { url: "/products/dates-premium-1kg.jpg", name: "Dates Premium 1Kg" },
  { url: "/products/deshi-egg-12pcs.jpg", name: "Deshi Egg 12Pcs" },
  { url: "/products/detergent-powder-500g.jpg", name: "Detergent Powder 500G" },
  { url: "/products/detergent.jpg", name: "Detergent" },
  { url: "/products/diaper.jpg", name: "Diaper" },
  { url: "/products/digestive-biscuit-250g.jpg", name: "Digestive Biscuit 250G" },
  { url: "/products/dishwash-liquid-500ml.jpg", name: "Dishwash Liquid 500Ml" },
  { url: "/products/dishwash.jpg", name: "Dishwash" },
  { url: "/products/egg.jpg", name: "Egg" },
  { url: "/products/farm-egg-12pcs.jpg", name: "Farm Egg 12Pcs" },
  { url: "/products/floor-cleaner-1l.jpg", name: "Floor Cleaner 1L" },
  { url: "/products/fresh-milk-1l.jpg", name: "Fresh Milk 1L" },
  { url: "/products/fresh-soyabean-oil-2l.jpg", name: "Fresh Soyabean Oil 2L" },
  { url: "/products/frozen-paratha-20pcs.jpg", name: "Frozen Paratha 20Pcs" },
  { url: "/products/frozen-singara-12pcs.jpg", name: "Frozen Singara 12Pcs" },
  { url: "/products/frutika-mango-1l.jpg", name: "Frutika Mango 1L" },
  { url: "/products/garam-masala-50g.jpg", name: "Garam Masala 50G" },
  { url: "/products/garbage-bag-30pcs.jpg", name: "Garbage Bag 30Pcs" },
  { url: "/products/green-chili-250g.jpg", name: "Green Chili 250G" },
  { url: "/products/green-tea-bag-25pcs.jpg", name: "Green Tea Bag 25Pcs" },
  { url: "/products/hand-wash-200ml.jpg", name: "Hand Wash 200Ml" },
  { url: "/products/honey.jpg", name: "Honey" },
  { url: "/products/ilish-fish-1kg.jpg", name: "Ilish Fish 1Kg" },
  { url: "/products/instant-noodles.jpg", name: "Instant Noodles" },
  { url: "/products/iodine-salt-1kg.jpg", name: "Iodine Salt 1Kg" },
  { url: "/products/ispahani-mirzapore-tea-500g.jpg", name: "Ispahani Mirzapore Tea 500G" },
  { url: "/products/katari-bhog-rice-5kg.jpg", name: "Katari Bhog Rice 5Kg" },
  { url: "/products/khesari-dal-1kg.jpg", name: "Khesari Dal 1Kg" },
  { url: "/products/kitkat-chocolate.jpg", name: "Kitkat Chocolate" },
  { url: "/products/maida-1kg.jpg", name: "Maida 1Kg" },
  { url: "/products/malta-1kg.jpg", name: "Malta 1Kg" },
  { url: "/products/marie-biscuit-300g.jpg", name: "Marie Biscuit 300G" },
  { url: "/products/masoor-dal-1kg.jpg", name: "Masoor Dal 1Kg" },
  { url: "/products/milk-bread-500g.jpg", name: "Milk Bread 500G" },
  { url: "/products/milk-vita-milk-500ml.jpg", name: "Milk Vita Milk 500Ml" },
  { url: "/products/milk.jpg", name: "Milk" },
  { url: "/products/miniket-rice-25kg.jpg", name: "Miniket Rice 25Kg" },
  { url: "/products/miniket-rice-5kg.jpg", name: "Miniket Rice 5Kg" },
  { url: "/products/mojo-500ml.jpg", name: "Mojo 500Ml" },
  { url: "/products/mr-noodles-8pack.jpg", name: "Mr Noodles 8Pack" },
  { url: "/products/mug-dal-1kg.jpg", name: "Mug Dal 1Kg" },
  { url: "/products/mum-water-2l.jpg", name: "Mum Water 2L" },
  { url: "/products/mustard-oil-500ml.jpg", name: "Mustard Oil 500Ml" },
  { url: "/products/nazirshail-rice-25kg.jpg", name: "Nazirshail Rice 25Kg" },
  { url: "/products/nescafe-classic-50g.jpg", name: "Nescafe Classic 50G" },
  { url: "/products/noodles.jpg", name: "Noodles" },
  { url: "/products/notebook-200page.jpg", name: "Notebook 200Page" },
  { url: "/products/onion.jpg", name: "Onion" },
  { url: "/products/pasteurized-milk-1l.jpg", name: "Pasteurized Milk 1L" },
  { url: "/products/pepsi-2l.jpg", name: "Pepsi 2L" },
  { url: "/products/potato-chips-100g.jpg", name: "Potato Chips 100G" },
  { url: "/products/potato-crackers.jpg", name: "Potato Crackers" },
  { url: "/products/potato.jpg", name: "Potato" },
  { url: "/products/powder-milk-1kg.jpg", name: "Powder Milk 1Kg" },
  { url: "/products/pran-mango-juice-250ml.jpg", name: "Pran Mango Juice 250Ml" },
  { url: "/products/pran-orange-juice-250ml.jpg", name: "Pran Orange Juice 250Ml" },
  { url: "/products/raisin-200g.jpg", name: "Raisin 200G" },
  { url: "/products/rice-bran-oil-1l.jpg", name: "Rice Bran Oil 1L" },
  { url: "/products/rui-fish-1kg.jpg", name: "Rui Fish 1Kg" },
  { url: "/products/rupchanda-soyabean-oil-5l.jpg", name: "Rupchanda Soyabean Oil 5L" },
  { url: "/products/salt-1kg.jpg", name: "Salt 1Kg" },
  { url: "/products/shampoo.jpg", name: "Shampoo" },
  { url: "/products/shaving-razor-3pcs.jpg", name: "Shaving Razor 3Pcs" },
  { url: "/products/shezan-apple-juice-1l.jpg", name: "Shezan Apple Juice 1L" },
  { url: "/products/shrimp-500g.jpg", name: "Shrimp 500G" },
  { url: "/products/soap.jpg", name: "Soap" },
  { url: "/products/soyabean-oil-1l.jpg", name: "Soyabean Oil 1L" },
  { url: "/products/spaghetti-pasta-400g.jpg", name: "Spaghetti Pasta 400G" },
  { url: "/products/speed-energy-drink-250ml.jpg", name: "Speed Energy Drink 250Ml" },
  { url: "/products/sprite-125l.jpg", name: "Sprite 125L" },
  { url: "/products/sugar-1kg.jpg", name: "Sugar 1Kg" },
  { url: "/products/sugar-5kg.jpg", name: "Sugar 5Kg" },
  { url: "/products/suji-500g.jpg", name: "Suji 500G" },
  { url: "/products/sweet-yogurt-500g.jpg", name: "Sweet Yogurt 500G" },
  { url: "/products/taaza-tea-400g.jpg", name: "Taaza Tea 400G" },
  { url: "/products/tea-leaf-400g.jpg", name: "Tea Leaf 400G" },
  { url: "/products/tissue-box.jpg", name: "Tissue Box" },
  { url: "/products/tissue.jpg", name: "Tissue" },
  { url: "/products/toilet-tissue-4roll.jpg", name: "Toilet Tissue 4Roll" },
  { url: "/products/tomato.jpg", name: "Tomato" },
  { url: "/products/toothbrush-2pcs.jpg", name: "Toothbrush 2Pcs" },
  { url: "/products/toothpaste-100g.jpg", name: "Toothpaste 100G" },
  { url: "/products/toothpaste.jpg", name: "Toothpaste" },
  { url: "/products/turmeric-powder-200g.jpg", name: "Turmeric Powder 200G" },
  { url: "/products/washing-powder-1kg.jpg", name: "Washing Powder 1Kg" },
  { url: "/products/water.jpg", name: "Water" },
  { url: "/products/yogurt.jpg", name: "Yogurt" },
];

import heroShade from "@/assets/hero-shade.jpg";
import cardShade from "@/assets/card-shade.jpg";

export const SITE_OTHER_IMAGES: { url: string; name: string; folder: string }[] = [
  { url: heroShade, name: "Hero Shade", folder: "banners" },
  { url: cardShade, name: "Card Shade", folder: "banners" },
];
