/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OrderConfirmedRouteImport } from './routes/order-confirmed'
import { Route as MyOrdersRouteImport } from './routes/my-orders'
import { Route as MyAccountRouteImport } from './routes/my-account'
import { Route as HomedeliveryRouteImport } from './routes/homedelivery'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedStockTransfersRouteImport } from './routes/_authenticated/stock-transfers'
import { Route as AuthenticatedStockCountRouteImport } from './routes/_authenticated/stock-count'
import { Route as AuthenticatedStockAdjustmentsRouteImport } from './routes/_authenticated/stock-adjustments'
import { Route as AuthenticatedSiteContentRouteImport } from './routes/_authenticated/site-content'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as AuthenticatedRidersRouteImport } from './routes/_authenticated/riders'
import { Route as AuthenticatedReviewsRouteImport } from './routes/_authenticated/reviews'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPurchasesRouteImport } from './routes/_authenticated/purchases'
import { Route as AuthenticatedPurchaseOrdersRouteImport } from './routes/_authenticated/purchase-orders'
import { Route as AuthenticatedPromotionsRouteImport } from './routes/_authenticated/promotions'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedProductAuditRouteImport } from './routes/_authenticated/product-audit'
import { Route as AuthenticatedPosRouteImport } from './routes/_authenticated/pos'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedPartyStatementRouteImport } from './routes/_authenticated/party-statement'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMobilePaymentsRouteImport } from './routes/_authenticated/mobile-payments'
import { Route as AuthenticatedMediaRouteImport } from './routes/_authenticated/media'
import { Route as AuthenticatedLabelsRouteImport } from './routes/_authenticated/labels'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedFinancialsRouteImport } from './routes/_authenticated/financials'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedDeliveryZonesRouteImport } from './routes/_authenticated/delivery-zones'
import { Route as AuthenticatedDeliveryOrdersRouteImport } from './routes/_authenticated/delivery-orders'
import { Route as AuthenticatedDayBookRouteImport } from './routes/_authenticated/day-book'
import { Route as AuthenticatedDataBackupRouteImport } from './routes/_authenticated/data-backup'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCouponsRouteImport } from './routes/_authenticated/coupons'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedCommerceRouteImport } from './routes/_authenticated/commerce'
import { Route as AuthenticatedChartOfAccountsRouteImport } from './routes/_authenticated/chart-of-accounts'
import { Route as AuthenticatedCatalogRouteImport } from './routes/_authenticated/catalog'
import { Route as AuthenticatedBranchesRouteImport } from './routes/_authenticated/branches'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated/audit-logs'
import { Route as AuthenticatedAssistantRouteImport } from './routes/_authenticated/assistant'
import { Route as AuthenticatedApiHubRouteImport } from './routes/_authenticated/api-hub'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated/accounts'

const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmedRoute = OrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrdersRoute = MyOrdersRouteImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAccountRoute = MyAccountRouteImport.update({
  id: '/my-account',
  path: '/my-account',
  getParentRoute: () => rootRouteImport,
} as any)
const HomedeliveryRoute = HomedeliveryRouteImport.update({
  id: '/homedelivery',
  path: '/homedelivery',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStockTransfersRoute =
  AuthenticatedStockTransfersRouteImport.update({
    id: '/stock-transfers',
    path: '/stock-transfers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStockCountRoute = AuthenticatedStockCountRouteImport.update({
  id: '/stock-count',
  path: '/stock-count',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStockAdjustmentsRoute =
  AuthenticatedStockAdjustmentsRouteImport.update({
    id: '/stock-adjustments',
    path: '/stock-adjustments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSiteContentRoute =
  AuthenticatedSiteContentRouteImport.update({
    id: '/site-content',
    path: '/site-content',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRidersRoute = AuthenticatedRidersRouteImport.update({
  id: '/riders',
  path: '/riders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewsRoute = AuthenticatedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchasesRoute = AuthenticatedPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPurchaseOrdersRoute =
  AuthenticatedPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPromotionsRoute = AuthenticatedPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductAuditRoute =
  AuthenticatedProductAuditRouteImport.update({
    id: '/product-audit',
    path: '/product-audit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPosRoute = AuthenticatedPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartyStatementRoute =
  AuthenticatedPartyStatementRouteImport.update({
    id: '/party-statement',
    path: '/party-statement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMobilePaymentsRoute =
  AuthenticatedMobilePaymentsRouteImport.update({
    id: '/mobile-payments',
    path: '/mobile-payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMediaRoute = AuthenticatedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLabelsRoute = AuthenticatedLabelsRouteImport.update({
  id: '/labels',
  path: '/labels',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinancialsRoute = AuthenticatedFinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeliveryZonesRoute =
  AuthenticatedDeliveryZonesRouteImport.update({
    id: '/delivery-zones',
    path: '/delivery-zones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeliveryOrdersRoute =
  AuthenticatedDeliveryOrdersRouteImport.update({
    id: '/delivery-orders',
    path: '/delivery-orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDayBookRoute = AuthenticatedDayBookRouteImport.update({
  id: '/day-book',
  path: '/day-book',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDataBackupRoute = AuthenticatedDataBackupRouteImport.update({
  id: '/data-backup',
  path: '/data-backup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCouponsRoute = AuthenticatedCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommerceRoute = AuthenticatedCommerceRouteImport.update({
  id: '/commerce',
  path: '/commerce',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChartOfAccountsRoute =
  AuthenticatedChartOfAccountsRouteImport.update({
    id: '/chart-of-accounts',
    path: '/chart-of-accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCatalogRoute = AuthenticatedCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBranchesRoute = AuthenticatedBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistantRoute = AuthenticatedAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApiHubRoute = AuthenticatedApiHubRouteImport.update({
  id: '/api-hub',
  path: '/api-hub',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/budget': typeof BudgetRoute
  '/corporate': typeof CorporateRoute
  '/homedelivery': typeof HomedeliveryRoute
  '/my-account': typeof MyAccountRoute
  '/my-orders': typeof MyOrdersRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/privacy': typeof PrivacyRoute
  '/shop': typeof ShopRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/api-hub': typeof AuthenticatedApiHubRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/chart-of-accounts': typeof AuthenticatedChartOfAccountsRoute
  '/commerce': typeof AuthenticatedCommerceRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/coupons': typeof AuthenticatedCouponsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data-backup': typeof AuthenticatedDataBackupRoute
  '/day-book': typeof AuthenticatedDayBookRoute
  '/delivery-orders': typeof AuthenticatedDeliveryOrdersRoute
  '/delivery-zones': typeof AuthenticatedDeliveryZonesRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/financials': typeof AuthenticatedFinancialsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/labels': typeof AuthenticatedLabelsRoute
  '/media': typeof AuthenticatedMediaRoute
  '/mobile-payments': typeof AuthenticatedMobilePaymentsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/party-statement': typeof AuthenticatedPartyStatementRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/pos': typeof AuthenticatedPosRoute
  '/product-audit': typeof AuthenticatedProductAuditRoute
  '/products': typeof AuthenticatedProductsRoute
  '/promotions': typeof AuthenticatedPromotionsRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/riders': typeof AuthenticatedRidersRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/site-content': typeof AuthenticatedSiteContentRoute
  '/stock-adjustments': typeof AuthenticatedStockAdjustmentsRoute
  '/stock-count': typeof AuthenticatedStockCountRoute
  '/stock-transfers': typeof AuthenticatedStockTransfersRoute
  '/users': typeof AuthenticatedUsersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/budget': typeof BudgetRoute
  '/corporate': typeof CorporateRoute
  '/homedelivery': typeof HomedeliveryRoute
  '/my-account': typeof MyAccountRoute
  '/my-orders': typeof MyOrdersRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/privacy': typeof PrivacyRoute
  '/shop': typeof ShopRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/api-hub': typeof AuthenticatedApiHubRoute
  '/assistant': typeof AuthenticatedAssistantRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/branches': typeof AuthenticatedBranchesRoute
  '/catalog': typeof AuthenticatedCatalogRoute
  '/chart-of-accounts': typeof AuthenticatedChartOfAccountsRoute
  '/commerce': typeof AuthenticatedCommerceRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/coupons': typeof AuthenticatedCouponsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/data-backup': typeof AuthenticatedDataBackupRoute
  '/day-book': typeof AuthenticatedDayBookRoute
  '/delivery-orders': typeof AuthenticatedDeliveryOrdersRoute
  '/delivery-zones': typeof AuthenticatedDeliveryZonesRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/financials': typeof AuthenticatedFinancialsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/labels': typeof AuthenticatedLabelsRoute
  '/media': typeof AuthenticatedMediaRoute
  '/mobile-payments': typeof AuthenticatedMobilePaymentsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/party-statement': typeof AuthenticatedPartyStatementRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/pos': typeof AuthenticatedPosRoute
  '/product-audit': typeof AuthenticatedProductAuditRoute
  '/products': typeof AuthenticatedProductsRoute
  '/promotions': typeof AuthenticatedPromotionsRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/purchases': typeof AuthenticatedPurchasesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/reviews': typeof AuthenticatedReviewsRoute
  '/riders': typeof AuthenticatedRidersRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/site-content': typeof AuthenticatedSiteContentRoute
  '/stock-adjustments': typeof AuthenticatedStockAdjustmentsRoute
  '/stock-count': typeof AuthenticatedStockCountRoute
  '/stock-transfers': typeof AuthenticatedStockTransfersRoute
  '/users': typeof AuthenticatedUsersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/budget': typeof BudgetRoute
  '/corporate': typeof CorporateRoute
  '/homedelivery': typeof HomedeliveryRoute
  '/my-account': typeof MyAccountRoute
  '/my-orders': typeof MyOrdersRoute
  '/order-confirmed': typeof OrderConfirmedRoute
  '/privacy': typeof PrivacyRoute
  '/shop': typeof ShopRoute
  '/signin': typeof SigninRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/api-hub': typeof AuthenticatedApiHubRoute
  '/_authenticated/assistant': typeof AuthenticatedAssistantRoute
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/branches': typeof AuthenticatedBranchesRoute
  '/_authenticated/catalog': typeof AuthenticatedCatalogRoute
  '/_authenticated/chart-of-accounts': typeof AuthenticatedChartOfAccountsRoute
  '/_authenticated/commerce': typeof AuthenticatedCommerceRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/coupons': typeof AuthenticatedCouponsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/data-backup': typeof AuthenticatedDataBackupRoute
  '/_authenticated/day-book': typeof AuthenticatedDayBookRoute
  '/_authenticated/delivery-orders': typeof AuthenticatedDeliveryOrdersRoute
  '/_authenticated/delivery-zones': typeof AuthenticatedDeliveryZonesRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/financials': typeof AuthenticatedFinancialsRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/labels': typeof AuthenticatedLabelsRoute
  '/_authenticated/media': typeof AuthenticatedMediaRoute
  '/_authenticated/mobile-payments': typeof AuthenticatedMobilePaymentsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/party-statement': typeof AuthenticatedPartyStatementRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/pos': typeof AuthenticatedPosRoute
  '/_authenticated/product-audit': typeof AuthenticatedProductAuditRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/promotions': typeof AuthenticatedPromotionsRoute
  '/_authenticated/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/_authenticated/purchases': typeof AuthenticatedPurchasesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/reviews': typeof AuthenticatedReviewsRoute
  '/_authenticated/riders': typeof AuthenticatedRidersRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/site-content': typeof AuthenticatedSiteContentRoute
  '/_authenticated/stock-adjustments': typeof AuthenticatedStockAdjustmentsRoute
  '/_authenticated/stock-count': typeof AuthenticatedStockCountRoute
  '/_authenticated/stock-transfers': typeof AuthenticatedStockTransfersRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/budget'
    | '/corporate'
    | '/homedelivery'
    | '/my-account'
    | '/my-orders'
    | '/order-confirmed'
    | '/privacy'
    | '/shop'
    | '/signin'
    | '/sitemap.xml'
    | '/terms'
    | '/track'
    | '/accounts'
    | '/api-hub'
    | '/assistant'
    | '/audit-logs'
    | '/branches'
    | '/catalog'
    | '/chart-of-accounts'
    | '/commerce'
    | '/contacts'
    | '/coupons'
    | '/dashboard'
    | '/data-backup'
    | '/day-book'
    | '/delivery-orders'
    | '/delivery-zones'
    | '/expenses'
    | '/financials'
    | '/inventory'
    | '/journal'
    | '/labels'
    | '/media'
    | '/mobile-payments'
    | '/notifications'
    | '/party-statement'
    | '/payments'
    | '/pos'
    | '/product-audit'
    | '/products'
    | '/promotions'
    | '/purchase-orders'
    | '/purchases'
    | '/reports'
    | '/reviews'
    | '/riders'
    | '/sales'
    | '/settings'
    | '/site-content'
    | '/stock-adjustments'
    | '/stock-count'
    | '/stock-transfers'
    | '/users'
    | '/category/$slug'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/budget'
    | '/corporate'
    | '/homedelivery'
    | '/my-account'
    | '/my-orders'
    | '/order-confirmed'
    | '/privacy'
    | '/shop'
    | '/signin'
    | '/sitemap.xml'
    | '/terms'
    | '/track'
    | '/accounts'
    | '/api-hub'
    | '/assistant'
    | '/audit-logs'
    | '/branches'
    | '/catalog'
    | '/chart-of-accounts'
    | '/commerce'
    | '/contacts'
    | '/coupons'
    | '/dashboard'
    | '/data-backup'
    | '/day-book'
    | '/delivery-orders'
    | '/delivery-zones'
    | '/expenses'
    | '/financials'
    | '/inventory'
    | '/journal'
    | '/labels'
    | '/media'
    | '/mobile-payments'
    | '/notifications'
    | '/party-statement'
    | '/payments'
    | '/pos'
    | '/product-audit'
    | '/products'
    | '/promotions'
    | '/purchase-orders'
    | '/purchases'
    | '/reports'
    | '/reviews'
    | '/riders'
    | '/sales'
    | '/settings'
    | '/site-content'
    | '/stock-adjustments'
    | '/stock-count'
    | '/stock-transfers'
    | '/users'
    | '/category/$slug'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/budget'
    | '/corporate'
    | '/homedelivery'
    | '/my-account'
    | '/my-orders'
    | '/order-confirmed'
    | '/privacy'
    | '/shop'
    | '/signin'
    | '/sitemap.xml'
    | '/terms'
    | '/track'
    | '/_authenticated/accounts'
    | '/_authenticated/api-hub'
    | '/_authenticated/assistant'
    | '/_authenticated/audit-logs'
    | '/_authenticated/branches'
    | '/_authenticated/catalog'
    | '/_authenticated/chart-of-accounts'
    | '/_authenticated/commerce'
    | '/_authenticated/contacts'
    | '/_authenticated/coupons'
    | '/_authenticated/dashboard'
    | '/_authenticated/data-backup'
    | '/_authenticated/day-book'
    | '/_authenticated/delivery-orders'
    | '/_authenticated/delivery-zones'
    | '/_authenticated/expenses'
    | '/_authenticated/financials'
    | '/_authenticated/inventory'
    | '/_authenticated/journal'
    | '/_authenticated/labels'
    | '/_authenticated/media'
    | '/_authenticated/mobile-payments'
    | '/_authenticated/notifications'
    | '/_authenticated/party-statement'
    | '/_authenticated/payments'
    | '/_authenticated/pos'
    | '/_authenticated/product-audit'
    | '/_authenticated/products'
    | '/_authenticated/promotions'
    | '/_authenticated/purchase-orders'
    | '/_authenticated/purchases'
    | '/_authenticated/reports'
    | '/_authenticated/reviews'
    | '/_authenticated/riders'
    | '/_authenticated/sales'
    | '/_authenticated/settings'
    | '/_authenticated/site-content'
    | '/_authenticated/stock-adjustments'
    | '/_authenticated/stock-count'
    | '/_authenticated/stock-transfers'
    | '/_authenticated/users'
    | '/category/$slug'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BudgetRoute: typeof BudgetRoute
  CorporateRoute: typeof CorporateRoute
  HomedeliveryRoute: typeof HomedeliveryRoute
  MyAccountRoute: typeof MyAccountRoute
  MyOrdersRoute: typeof MyOrdersRoute
  OrderConfirmedRoute: typeof OrderConfirmedRoute
  PrivacyRoute: typeof PrivacyRoute
  ShopRoute: typeof ShopRoute
  SigninRoute: typeof SigninRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmed': {
      id: '/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/order-confirmed'
      preLoaderRoute: typeof OrderConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-orders': {
      id: '/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof MyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-account': {
      id: '/my-account'
      path: '/my-account'
      fullPath: '/my-account'
      preLoaderRoute: typeof MyAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homedelivery': {
      id: '/homedelivery'
      path: '/homedelivery'
      fullPath: '/homedelivery'
      preLoaderRoute: typeof HomedeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock-transfers': {
      id: '/_authenticated/stock-transfers'
      path: '/stock-transfers'
      fullPath: '/stock-transfers'
      preLoaderRoute: typeof AuthenticatedStockTransfersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock-count': {
      id: '/_authenticated/stock-count'
      path: '/stock-count'
      fullPath: '/stock-count'
      preLoaderRoute: typeof AuthenticatedStockCountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock-adjustments': {
      id: '/_authenticated/stock-adjustments'
      path: '/stock-adjustments'
      fullPath: '/stock-adjustments'
      preLoaderRoute: typeof AuthenticatedStockAdjustmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/site-content': {
      id: '/_authenticated/site-content'
      path: '/site-content'
      fullPath: '/site-content'
      preLoaderRoute: typeof AuthenticatedSiteContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/riders': {
      id: '/_authenticated/riders'
      path: '/riders'
      fullPath: '/riders'
      preLoaderRoute: typeof AuthenticatedRidersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reviews': {
      id: '/_authenticated/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchases': {
      id: '/_authenticated/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AuthenticatedPurchasesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/purchase-orders': {
      id: '/_authenticated/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/promotions': {
      id: '/_authenticated/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof AuthenticatedPromotionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/product-audit': {
      id: '/_authenticated/product-audit'
      path: '/product-audit'
      fullPath: '/product-audit'
      preLoaderRoute: typeof AuthenticatedProductAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pos': {
      id: '/_authenticated/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AuthenticatedPosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/party-statement': {
      id: '/_authenticated/party-statement'
      path: '/party-statement'
      fullPath: '/party-statement'
      preLoaderRoute: typeof AuthenticatedPartyStatementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mobile-payments': {
      id: '/_authenticated/mobile-payments'
      path: '/mobile-payments'
      fullPath: '/mobile-payments'
      preLoaderRoute: typeof AuthenticatedMobilePaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media': {
      id: '/_authenticated/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedMediaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/labels': {
      id: '/_authenticated/labels'
      path: '/labels'
      fullPath: '/labels'
      preLoaderRoute: typeof AuthenticatedLabelsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financials': {
      id: '/_authenticated/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof AuthenticatedFinancialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delivery-zones': {
      id: '/_authenticated/delivery-zones'
      path: '/delivery-zones'
      fullPath: '/delivery-zones'
      preLoaderRoute: typeof AuthenticatedDeliveryZonesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delivery-orders': {
      id: '/_authenticated/delivery-orders'
      path: '/delivery-orders'
      fullPath: '/delivery-orders'
      preLoaderRoute: typeof AuthenticatedDeliveryOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/day-book': {
      id: '/_authenticated/day-book'
      path: '/day-book'
      fullPath: '/day-book'
      preLoaderRoute: typeof AuthenticatedDayBookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/data-backup': {
      id: '/_authenticated/data-backup'
      path: '/data-backup'
      fullPath: '/data-backup'
      preLoaderRoute: typeof AuthenticatedDataBackupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coupons': {
      id: '/_authenticated/coupons'
      path: '/coupons'
      fullPath: '/coupons'
      preLoaderRoute: typeof AuthenticatedCouponsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commerce': {
      id: '/_authenticated/commerce'
      path: '/commerce'
      fullPath: '/commerce'
      preLoaderRoute: typeof AuthenticatedCommerceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chart-of-accounts': {
      id: '/_authenticated/chart-of-accounts'
      path: '/chart-of-accounts'
      fullPath: '/chart-of-accounts'
      preLoaderRoute: typeof AuthenticatedChartOfAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalog': {
      id: '/_authenticated/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof AuthenticatedCatalogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/branches': {
      id: '/_authenticated/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof AuthenticatedBranchesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistant': {
      id: '/_authenticated/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AuthenticatedAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/api-hub': {
      id: '/_authenticated/api-hub'
      path: '/api-hub'
      fullPath: '/api-hub'
      preLoaderRoute: typeof AuthenticatedApiHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedApiHubRoute: typeof AuthenticatedApiHubRoute
  AuthenticatedAssistantRoute: typeof AuthenticatedAssistantRoute
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedBranchesRoute: typeof AuthenticatedBranchesRoute
  AuthenticatedCatalogRoute: typeof AuthenticatedCatalogRoute
  AuthenticatedChartOfAccountsRoute: typeof AuthenticatedChartOfAccountsRoute
  AuthenticatedCommerceRoute: typeof AuthenticatedCommerceRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedCouponsRoute: typeof AuthenticatedCouponsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDataBackupRoute: typeof AuthenticatedDataBackupRoute
  AuthenticatedDayBookRoute: typeof AuthenticatedDayBookRoute
  AuthenticatedDeliveryOrdersRoute: typeof AuthenticatedDeliveryOrdersRoute
  AuthenticatedDeliveryZonesRoute: typeof AuthenticatedDeliveryZonesRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedFinancialsRoute: typeof AuthenticatedFinancialsRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedLabelsRoute: typeof AuthenticatedLabelsRoute
  AuthenticatedMediaRoute: typeof AuthenticatedMediaRoute
  AuthenticatedMobilePaymentsRoute: typeof AuthenticatedMobilePaymentsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPartyStatementRoute: typeof AuthenticatedPartyStatementRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPosRoute: typeof AuthenticatedPosRoute
  AuthenticatedProductAuditRoute: typeof AuthenticatedProductAuditRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedPromotionsRoute: typeof AuthenticatedPromotionsRoute
  AuthenticatedPurchaseOrdersRoute: typeof AuthenticatedPurchaseOrdersRoute
  AuthenticatedPurchasesRoute: typeof AuthenticatedPurchasesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedReviewsRoute: typeof AuthenticatedReviewsRoute
  AuthenticatedRidersRoute: typeof AuthenticatedRidersRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSiteContentRoute: typeof AuthenticatedSiteContentRoute
  AuthenticatedStockAdjustmentsRoute: typeof AuthenticatedStockAdjustmentsRoute
  AuthenticatedStockCountRoute: typeof AuthenticatedStockCountRoute
  AuthenticatedStockTransfersRoute: typeof AuthenticatedStockTransfersRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedApiHubRoute: AuthenticatedApiHubRoute,
  AuthenticatedAssistantRoute: AuthenticatedAssistantRoute,
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedBranchesRoute: AuthenticatedBranchesRoute,
  AuthenticatedCatalogRoute: AuthenticatedCatalogRoute,
  AuthenticatedChartOfAccountsRoute: AuthenticatedChartOfAccountsRoute,
  AuthenticatedCommerceRoute: AuthenticatedCommerceRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedCouponsRoute: AuthenticatedCouponsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDataBackupRoute: AuthenticatedDataBackupRoute,
  AuthenticatedDayBookRoute: AuthenticatedDayBookRoute,
  AuthenticatedDeliveryOrdersRoute: AuthenticatedDeliveryOrdersRoute,
  AuthenticatedDeliveryZonesRoute: AuthenticatedDeliveryZonesRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedFinancialsRoute: AuthenticatedFinancialsRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedLabelsRoute: AuthenticatedLabelsRoute,
  AuthenticatedMediaRoute: AuthenticatedMediaRoute,
  AuthenticatedMobilePaymentsRoute: AuthenticatedMobilePaymentsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPartyStatementRoute: AuthenticatedPartyStatementRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPosRoute: AuthenticatedPosRoute,
  AuthenticatedProductAuditRoute: AuthenticatedProductAuditRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedPromotionsRoute: AuthenticatedPromotionsRoute,
  AuthenticatedPurchaseOrdersRoute: AuthenticatedPurchaseOrdersRoute,
  AuthenticatedPurchasesRoute: AuthenticatedPurchasesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedReviewsRoute: AuthenticatedReviewsRoute,
  AuthenticatedRidersRoute: AuthenticatedRidersRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSiteContentRoute: AuthenticatedSiteContentRoute,
  AuthenticatedStockAdjustmentsRoute: AuthenticatedStockAdjustmentsRoute,
  AuthenticatedStockCountRoute: AuthenticatedStockCountRoute,
  AuthenticatedStockTransfersRoute: AuthenticatedStockTransfersRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BudgetRoute: BudgetRoute,
  CorporateRoute: CorporateRoute,
  HomedeliveryRoute: HomedeliveryRoute,
  MyAccountRoute: MyAccountRoute,
  MyOrdersRoute: MyOrdersRoute,
  OrderConfirmedRoute: OrderConfirmedRoute,
  PrivacyRoute: PrivacyRoute,
  ShopRoute: ShopRoute,
  SigninRoute: SigninRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
